### ISSUE TITLE
Server side crash

### ISSUE THREAD

**Issue by Everhate** [joe-vettek/Fluid-Drawers-Legacy#6]
## Game Version, Launcher Version, Mod Version

MC 1.16.5

Forge 36.2.20

Fluid Drawers Legacy 1.0

## Problem Description

Repeatable, Requires 2 Fluid Drawers same liquid, (was using Creosote oil from IE)
Upon 2nd tank filling up (both using 1 redstone upgrade and rest emerald upgrades) server would crash

Simply Draining 2nd tank would temp fix this

(BTW great job on this mod)

## Crash Log

---- Minecraft Crash Report ----

Time: 7/22/22 8:11 PM
Description: Exception in server tick loop

java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_191] {}
	at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_191] {}
	at xueluoanping.fluiddrawerslegacy.capability.CapabilityProvider_FluidDrawerController$betterFluidHandler.fillByOrder(CapabilityProvider_FluidDrawerController.java:235) ~[fluiddrawerslegacy:1.16.5-forge-1.1.0-universal] {re:classloading}
	at xueluoanping.fluiddrawerslegacy.capability.CapabilityProvider_FluidDrawerController$betterFluidHandler.fill(CapabilityProvider_FluidDrawerController.java:305) ~[fluiddrawerslegacy:1.16.5-forge-1.1.0-universal] {re:classloading}
	at mekanism.common.util.FluidUtils.canFill(FluidUtils.java:72) ~[mekanism:10.1.2] {re:classloading}
	at mekanism.common.content.network.FluidNetwork.lambda$tickEmit$0(FluidNetwork.java:158) ~[mekanism:10.1.2] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:165) ~[forge:?] {re:classloading}
	at mekanism.common.content.network.FluidNetwork.tickEmit(FluidNetwork.java:157) ~[mekanism:10.1.2] {re:classloading}
	at mekanism.common.content.network.FluidNetwork.onUpdate(FluidNetwork.java:177) ~[mekanism:10.1.2] {re:classloading}
	at mekanism.common.lib.transmitter.TransmitterNetworkRegistry.onTick(TransmitterNetworkRegistry.java:114) ~[mekanism:10.1.2] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_552_TransmitterNetworkRegistry_onTick_ServerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:120) ~[forge:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:828) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191] {}

**Comment by joe-vettek** [comment]
thank you for your compliment, but Sorry I can't reproduce your operation.
And I notice that your version was 1.1.0-universal while the latest version is 1.1.0-fix in Jun 6, 2022.
1.1.0-universal was deleted fo some mistakes.

**Comment by joe-vettek** [comment]
Sorry for not replying for so long, because I'm busy.
